import Link from "next/link";
import { getServerSession } from "next-auth";
import { CalendarDays, Target, AlertTriangle } from "lucide-react";
import { authOptions } from "@/lib/auth";
import { readStore } from "@/lib/json/store";
export const dynamic = "force-dynamic";
export default async function PlannerPage(){
 const session=await getServerSession(authOptions); const userId=session!.user.id; const store=await readStore();
 const games=new Map(store.games.filter(g=>g.userId===userId).map(g=>[g.appId,g])); const summaries=new Map(store.achievementSummaries.filter(s=>s.userId===userId).map(s=>[s.appId,s]));
 const items=store.gameObjectives.filter(o=>o.userId===userId).filter(o=>o.status!=="COMPLETED").sort((a,b)=>{if(a.targetDate&&b.targetDate)return a.targetDate.localeCompare(b.targetDate); if(a.targetDate)return-1;if(b.targetDate)return 1; return b.priority.localeCompare(a.priority);});
 const now=Date.now();
 return <div className="flex flex-col gap-6"><header><p className="text-xs uppercase tracking-[0.22em] text-steam">Organisation</p><h1 className="mt-2 flex items-center gap-3 font-display text-3xl font-bold text-white"><CalendarDays className="h-7 w-7 text-steam"/>Planificateur</h1><p className="mt-2 text-sm text-slate-400">Tes objectifs triés par échéance pour savoir quoi terminer ensuite.</p></header>
 {items.length===0?<div className="glass-panel p-10 text-center"><Target className="mx-auto h-8 w-8 text-steam"/><h2 className="mt-3 text-lg font-semibold text-white">Aucune échéance active</h2><p className="mt-2 text-sm text-slate-400">Ajoute une date cible depuis la fiche d’un jeu.</p><Link href="/games" className="mt-5 inline-flex rounded-xl bg-steam px-4 py-2 text-sm font-semibold text-[#07111b]">Choisir un jeu</Link></div>:<div className="grid gap-4">{items.map(o=>{const game=games.get(o.appId);const summary=summaries.get(o.appId);const overdue=o.targetDate?new Date(o.targetDate).getTime()<now:false;return <Link href={`/games/${o.appId}`} key={o.appId} className="glass-panel grid gap-4 p-5 transition hover:border-steam/30 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-semibold text-white">{game?.name??`Jeu ${o.appId}`}</h2><span className={`rounded-full px-2 py-1 text-[10px] ${o.priority==="HIGH"?"bg-rose-500/15 text-rose-300":o.priority==="MEDIUM"?"bg-amber-500/15 text-amber-300":"bg-slate-500/15 text-slate-300"}`}>Priorité {o.priority==="HIGH"?"haute":o.priority==="MEDIUM"?"normale":"faible"}</span>{overdue&&<span className="inline-flex items-center gap-1 rounded-full bg-rose-500/15 px-2 py-1 text-[10px] text-rose-300"><AlertTriangle className="h-3 w-3"/>En retard</span>}</div><p className="mt-2 text-sm text-slate-400">{o.note||"Aucune note personnelle."}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-steam" style={{width:`${summary?.percentage??0}%`}}/></div></div><div className="text-left md:text-right"><p className="font-mono text-2xl font-bold text-white">{summary?.percentage??0}%</p><p className="mt-1 text-xs text-slate-500">{o.targetDate?new Date(o.targetDate).toLocaleDateString("fr-FR"):"Sans date cible"}</p></div></Link>})}</div>}
 </div>
}
