"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Check, Crosshair, RefreshCw, ShieldCheck, Target, Trophy } from "lucide-react";
import { useGameModes } from "@/lib/games/useGameModes";

type HuntEntry = { achievement:{appId:number;apiName:string;displayName:string;iconGrayUrl:string|null;iconUrl:string|null}; game:{appId:number;name:string}; summary:{total:number;unlocked:number;percentage:number}; score:number };
type ModeFilter = "all"|"solo"|"online"|"mixed";
type Objective={id:string;label:string;selected:boolean;completed:boolean;points:number};
type Hunt={id:string;dateKey:string;appId:number;achievementApiName:string|null;mode:ModeFilter;status:"DRAFT"|"ACTIVE"|"COMPLETED"|"EXPIRED";objectives:Objective[];awardedXp:number;awardedHuntPoints:number};

const labels:Record<ModeFilter,string>={all:"Tous",solo:"Solo uniquement",online:"En ligne uniquement",mixed:"Solo + en ligne"};

export function HuntModeClient({entries,initialHunt}:{entries:HuntEntry[];initialHunt:Hunt|null}){
 const [mode,setMode]=useState<ModeFilter>("all");
 const [hunt,setHunt]=useState<Hunt|null>(initialHunt);
 const [selected,setSelected]=useState<string[]>(initialHunt?.objectives.filter(o=>o.selected).map(o=>o.id)??[]);
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const appIds=useMemo(()=>[...new Set(entries.map(e=>e.game.appId))],[entries]);
 const {modes,loading}=useGameModes(appIds);
 const eligibleAppIds=useMemo(()=>[...new Set(entries.filter(e=>mode==="all"||(modes[e.game.appId]??"unknown")===mode).map(e=>e.game.appId))],[entries,mode,modes]);
 const activeEntry=useMemo(()=>hunt?entries.find(e=>e.game.appId===hunt.appId&&(!hunt.achievementApiName||e.achievement.apiName===hunt.achievementApiName))??entries.find(e=>e.game.appId===hunt.appId)??null:null,[hunt,entries]);
 useEffect(()=>{if(hunt)setSelected(hunt.objectives.filter(o=>o.selected).map(o=>o.id))},[hunt]);
 async function start(){setBusy(true);setMessage(null);try{const r=await fetch('/api/fullclear/hunt/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,eligibleAppIds})});const d=await r.json();if(!r.ok)throw new Error(d.error);setHunt(d.hunt)}catch(e){setMessage(e instanceof Error?e.message:'Erreur')}finally{setBusy(false)}}
 async function confirm(){if(selected.length!==3)return;setBusy(true);setMessage(null);try{const r=await fetch('/api/fullclear/hunt/select',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({objectiveIds:selected})});const d=await r.json();if(!r.ok)throw new Error(d.error);setHunt(h=>h?{...h,status:'ACTIVE',objectives:h.objectives.map(o=>({...o,selected:selected.includes(o.id)}))}:h)}catch(e){setMessage(e instanceof Error?e.message:'Erreur')}finally{setBusy(false)}}
 async function verify(){setBusy(true);setMessage(null);try{const r=await fetch('/api/fullclear/hunt/verify',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.completed?`HUNT VALIDÉE · +${d.awardedXp} XP · +${d.awardedPoints} points`:`${d.newUnlocks} nouveau(x) succès · ${d.playtimeGain} min · objectifs incomplets`);location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Erreur')}finally{setBusy(false)}}
 return <div className="space-y-6">
  <header className="code-hero"><div><p className="code-kicker">$ fullclear hunt --daily --ranked</p><h1 className="mt-3 text-4xl font-black text-white">Hunt classée quotidienne</h1><p className="mt-3 max-w-2xl text-sm text-slate-400">Une seule Hunt par jour. Le jeu est tiré au hasard, tu choisis 3 objectifs sur 5, puis Steam valide automatiquement ta progression.</p></div><Crosshair className="h-24 w-24 text-emerald-300/20"/></header>
  {!hunt?<section className="terminal-card p-6"><p className="text-xs uppercase tracking-[.18em] text-emerald-300/55">Type de Hunt</p><div className="mt-4 flex flex-wrap gap-2">{(Object.keys(labels) as ModeFilter[]).map(x=><button key={x} onClick={()=>setMode(x)} className={`rounded-full border px-4 py-2 text-xs ${mode===x?'border-emerald-300/40 bg-emerald-300/10 text-white':'border-white/10 text-slate-400'}`}>{labels[x]}</button>)}</div><div className="mt-5 flex items-center justify-between border-t border-emerald-400/10 pt-5"><p className="text-xs text-slate-500">{loading?'Analyse Steam…':`${eligibleAppIds.length} jeux compatibles`}</p><button className="cyber-button" disabled={busy||loading||!eligibleAppIds.length} onClick={start}><Crosshair className="h-4 w-4"/>{busy?'Tirage…':'Tirer la Hunt du jour'}</button></div></section>:null}
  {hunt&&activeEntry?<section className="mission-card overflow-hidden"><div className="relative min-h-[360px] overflow-hidden rounded-[22px]"><Image src={`https://cdn.akamai.steamstatic.com/steam/apps/${activeEntry.game.appId}/header.jpg`} alt="" fill unoptimized className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#04100a] via-[#04100a]/94 to-[#04100a]/55"/><div className="relative z-10 grid gap-8 p-7 lg:grid-cols-[1fr_.9fr]"><div className="flex flex-col justify-end"><p className="text-xs uppercase tracking-[.18em] text-emerald-300/60">Hunt {hunt.dateKey} · {hunt.status}</p><h2 className="mt-3 text-4xl font-black text-white">{activeEntry.game.name}</h2><p className="mt-3 text-slate-300">Cible prioritaire : <strong className="text-white">{activeEntry.achievement.displayName}</strong></p><p className="mt-2 text-xs text-slate-500">{activeEntry.summary.unlocked}/{activeEntry.summary.total} · {activeEntry.summary.percentage}%</p><Link href={`/games/${activeEntry.game.appId}`} className="cyber-button mt-6 w-fit"><Trophy className="h-4 w-4"/>Ouvrir le jeu</Link></div><div className="hunt-objectives-panel"><div className="flex items-center gap-2 text-xs uppercase tracking-[.16em] text-emerald-200/55"><Target className="h-4 w-4"/>Choisis 3 objectifs</div><div className="mt-4 space-y-2">{hunt.objectives.map(o=>{const checked=selected.includes(o.id);return <button key={o.id} disabled={hunt.status!=="DRAFT"} onClick={()=>setSelected(s=>checked?s.filter(id=>id!==o.id):s.length<3?[...s,o.id]:s)} className={`hunt-objective w-full ${o.completed?'done':''} ${checked?'ring-1 ring-emerald-300/50':''}`}><Check className="h-4 w-4"/><span className="flex-1 text-left">{o.label}</span><strong>+{o.points}</strong></button>})}</div>{hunt.status==="DRAFT"?<button onClick={confirm} disabled={busy||selected.length!==3} className="cyber-button mt-5 w-full justify-center"><ShieldCheck className="h-4 w-4"/>Verrouiller les 3 objectifs</button>:null}{hunt.status==="ACTIVE"?<button onClick={verify} disabled={busy} className="cyber-button mt-5 w-full justify-center"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>Synchroniser et vérifier la Hunt</button>:null}{hunt.status==="COMPLETED"?<div className="mt-5 rounded-xl border border-emerald-300/25 bg-emerald-300/10 p-4 text-center"><p className="font-black text-emerald-200">HUNT VALIDÉE</p><p className="mt-1 text-xs text-slate-300">+{hunt.awardedXp} XP · +{hunt.awardedHuntPoints} points Hunt</p></div>:null}</div></div></div></section>:null}
  {message?<div className="terminal-card border-emerald-300/20 p-4 text-sm text-emerald-200">{message}</div>:null}
 </div>
}
